## **Neural Networks from Scratch**

We have already build a few Neural Networks in recent workshops using Tensorflow. But that's a third party library which we are using to build neural networks. But to really understand Neural Networks we must code layers from scratch in Python, so our intuition regarding Neural Networks will have another strong grip. We will continue working with some advanced Neural Networks in Tensorflow in our coming workshops, but it'll be a fun and a good practice to see behind the scenes of so-called Neural Networks. 

---

If you may remember the simplest equation of simple layer. 

***y = w1x1 + w2x2 + w3x3 + ... + wnxn + b***

Where b = bias.

**Creates a basic neuron with 3 inputs.**

In [3]:
#Assuming values

inputs =  [1.2, 5.1, 2.1]    #Input Layer with 3 units or Neuron
weights = [3.1, 2.1, 8.7]    #Weights of Vectors
bias =    3.0                #Bias

#Implementing that equation in code, which is obv not so hard, is it?

output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + bias

#By printing this we are getting to know that, what output this layer will generate
print(output)

35.7


In [4]:
inputs =   [1.0, 2.0, 3.0, 2.5]       #Input Layer with 4 units or Neurons

weights1 = [0.2, 0.8, -0.5, 1.0]      
                                      #Hidden Layer 1 with 4 units or Neurons
weights2 = [0.5, -0.91, 0.26, -0.5]   
                                      #Hidden Layer 2 with 4 units or Neurons
weights3 = [-0.26, -0.27, 0.17, 0.87] 
                                      #Moving to Output Layer
bias1 =    2.0
bias2 =    3.0
bias3 =    0.5

output = [inputs[0]*weights1[0] + inputs[1]*weights1[1] + inputs[2]*weights1[2] + inputs[3]*weights1[3] + bias1,
          inputs[0]*weights2[0] + inputs[1]*weights2[1] + inputs[2]*weights2[2] + inputs[3]*weights2[3] + bias2,
          inputs[0]*weights3[0] + inputs[1]*weights3[1] + inputs[2]*weights3[2] + inputs[3]*weights3[3] + bias3]
print(output)

[4.8, 1.21, 2.385]


In [5]:
import numpy as np

inputs =  [1.0, 2.0, 3.0, 2.5]
weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases =  [2.0, 3.0, 0.5]

output =  np.dot(weights, inputs) + biases
print(output)

[4.8   1.21  2.385]


Layers and Objects

In [6]:
import numpy as np 

np.random.seed(0)

X = [[1, 2, 3, 2.5],
     [2.0, 5.0, -1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]]


class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

layer1 = Layer_Dense(4,5)
layer2 = Layer_Dense(5,2)

layer1.forward(X)
print("Layer 01\n", layer1.output)
layer2.forward(layer1.output)
print("Layer 02\n",layer2.output)

Layer 01
 [[ 0.10758131  1.03983522  0.24462411  0.31821498  0.18851053]
 [-0.08349796  0.70846411  0.00293357  0.44701525  0.36360538]
 [-0.50763245  0.55688422  0.07987797 -0.34889573  0.04553042]]
Layer 02
 [[ 0.148296   -0.08397602]
 [ 0.14100315 -0.01340469]
 [ 0.20124979 -0.07290616]]


In [7]:
!pip install nnfs

In [8]:
import numpy as np 
import nnfs
from nnfs.datasets import spiral_data  # See for code: https://gist.github.com/Sentdex/454cb20ec5acf0e76ee8ab8448e6266c

nnfs.init()

X, y = spiral_data(100, 3)   


class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases


class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)


layer1 = Layer_Dense(2,5)
activation1 = Activation_ReLU()

layer1.forward(X)

print("Layer 01\n",layer1.output)
activation1.forward(layer1.output)
print("Layer 02\n",activation1.output)

Layer 01
 [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [-8.35815910e-04 -7.90404272e-04 -1.33452227e-03  4.65504505e-04
   4.56846210e-05]
 [-2.39994470e-03  5.93469958e-05 -2.24808278e-03  2.03573116e-04
   6.10024377e-04]
 ...
 [ 1.13291524e-01 -1.89262271e-01 -2.06855070e-02  8.11079666e-02
  -6.71350807e-02]
 [ 1.34588361e-01 -1.43197834e-01  3.09493970e-02  5.66337556e-02
  -6.29687458e-02]
 [ 1.07817926e-01 -2.00809643e-01 -3.37579325e-02  8.72561932e-02
  -6.81458861e-02]]
Layer 02
 [[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 4.65504505e-04
  4.56846210e-05]
 [0.00000000e+00 5.93469958e-05 0.00000000e+00 2.03573116e-04
  6.10024377e-04]
 ...
 [1.13291524e-01 0.00000000e+00 0.00000000e+00 8.11079666e-02
  0.00000000e+00]
 [1.34588361e-01 0.00000000e+00 3.09493970e-02 5.66337556e-02
  0.00000000e+00]
 [1.07817926e-01 0.00000000e+00 0.00000000e+00 8.72561932e-